---
title: "Interactive Plots"
author: "D. Spence"
date: "December 5, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

### A Few Powerful R Libraries  

- googleVis
- plotly
- leaflet

```{r echo=TRUE, message=FALSE, warning=FALSE}
library(googleVis)
library(plotly)
library(leaflet)
```

## googleVis Motion Chart - The Data

This example uses the Fruits data set.

```{r echo=TRUE}
data("Fruits")
Fruits
```

## googleVis Motion Chart - The Code

```{r echo=TRUE, eval=FALSE}
M <- gvisMotionChart(data = Fruits, 
                     idvar = "Fruit", 
                     timevar = "Year", 
                     options = list(width=600, height=400))
#OR
M <- gvisMotionChart(Fruits, "Fruit", "Year", 
                     options = list(width=600, height=400))
```

To save the chart as a stand-alone HTML file:  
```{r echo=TRUE, eval=FALSE}
print(M, file="FruitMotionPlot.html")
```

To embed plot in RMarkdown document:  
Use results='asis' in r chunk options.  
```{r echo=TRUE, eval=FALSE}
print(M, tag='chart')
```

## googleVis Motion Chart - The Plot

```{r results='asis'}
M <- gvisMotionChart(Fruits, "Fruit", "Year", 
                     options = list(width=600, height=400))
print(M, tag='chart')
```

