---
title: "Interactive Maps with Leaflet"
author: "D. Spence"
date: "December 5, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r message=FALSE, warning=FALSE}
library(leaflet)
```


## Leaflet Simple Example - The Code
```{r echo=TRUE, eval=FALSE}
myMap <- leaflet() %>% 
    addTiles() %>%
    addMarkers(lat=34.52954,lng=-83.98419, 
               popup="UNG - Newton Oakes" )

myMap
```

## Leaflet Simple Example - The Map
```{r}
myMap <- leaflet() %>% 
    addTiles() %>%
    addMarkers(lat=34.52954,lng=-83.98419, popup="UNG - Newton Oakes" )

myMap
```

## Leaflet Custom Icon - The Code
```{r echo=TRUE, eval=FALSE}
UNGIcon <- makeIcon(
   iconUrl = "http://ung.edu/university-relations/_uploads/images/visual-identity-elements/UNG_SteepleMark_2c_121x200.png", 
   iconWidth = 30, iconHeight = 50, 
   iconAnchorX = 15, iconAnchorY = 25
)

myMap <- leaflet() %>% 
    addTiles() %>%
    addMarkers(lat=34.52954,lng=-83.98419, 
               popup="UNG - Newton Oakes", icon=UNGIcon)

myMap
```

## Leaflet Custom Icon - The Map
```{r}
UNGIcon <- makeIcon(
   iconUrl = "http://ung.edu/university-relations/_uploads/images/visual-identity-elements/UNG_SteepleMark_2c_121x200.png", 
   iconWidth = 30, iconHeight = 50, 
   iconAnchorX = 15, iconAnchorY = 25
)

myMap <- leaflet() %>% 
    addTiles() %>%
    addMarkers(lat=34.52954,lng=-83.98419, 
               popup="UNG - Newton Oakes", icon=UNGIcon)

myMap
```



